import { useState, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { useMutation } from "@tanstack/react-query";
import { useDropzone } from "react-dropzone";
import { v4 as uuidv4 } from 'uuid';
import { supabase } from "@/integrations/supabase/client";
import { ComplaintForm } from "@/components/complaints/ComplaintForm";
import { LanguageSelectionDialog } from "@/components/complaints/LanguageSelectionDialog";
import { ComplaintsNav } from "@/components/complaints/ComplaintsNav";
import { useLanguage } from "@/contexts/LanguageContext";
import { useToast } from "@/components/ui/use-toast";
import type { Sector } from "@/types/complaints";
import type { SubmissionType, LanguageCode } from "@/types/complaints";
import { AudioRecorder } from "@/components/AudioRecorder";

export const TRANSLATIONS = {
  english: {
    newComplaint: "New Complaint",
    complaintForm: "Complaint Form",
    success: "Success",
    complaintSubmitted: "Complaint submitted successfully!",
    error: "Error",
    complaintFailed: "Failed to submit complaint",
    titleLabel: "Title",
    descriptionLabel: "Description",
    sectorLabel: "Sector",
    submitButton: "Submit",
    uploadFiles: "Upload Files",
    dropFilesHere: "Drop files here, or click to select files",
    audioRecording: "Audio Recording",
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    recordComplaint: "Record your complaint",
    platformExperience: "Platform Experience",
    responseTime: "Response Time",
    accessibility: "Accessibility",
    other: "Other",
    feedbackCategory: "Feedback Category",
    name: "Name",
    email: "Email",
    optional: "Optional",
    required: "Required",
    selectState: "Select State",
    selectDistrict: "Select District",
    dateOfIncident: "Date of Incident",
    languageSelect: "English",
    successStories: "Success Stories",
    resources: "Resources",
    peerSupport: "Peer Support",
    liveQA: "Live Q&A",
    aiHelp: "AI Help",
    changeLanguage: "Change Language",
    viewDashboard: "View Dashboard",
    loading: "Loading...",
    complaintNotFound: "Complaint not found",
    backToComplaints: "Back to Complaints",
    by: "By",
    anonymous: "Anonymous",
    submittedOn: "Submitted on",
    updateStatus: "Update status",
    updates: "Updates",
    addUpdate: "Add an update...",
    adding: "Adding...",
    status: {
      pending: "Pending",
      in_progress: "In Progress",
      resolved: "Resolved",
      rejected: "Rejected"
    },
    helpTitle: "How can we help?",
    helpStep1Title: "Step 1: Describe your issue",
    helpStep1Content: "Clearly and concisely describe the issue you are facing. Provide as much detail as possible, including dates, times, locations, and people involved.",
    helpStep2Title: "Step 2: Gather supporting evidence",
    helpStep2Items: [
      "Collect any documents, photos, videos, or other evidence that supports your claim.",
      "Make sure your evidence is relevant and clearly labeled.",
      "If you have witnesses, ask them to provide a written statement."
    ],
    helpStep3Title: "Step 3: Submit your complaint",
    helpStep3Content: "Once you have gathered all the necessary information, submit your complaint through our online form. Be sure to fill out all required fields and attach any supporting evidence.",
    helpTipsTitle: "Tips for writing an effective complaint",
    helpTipsItems: [
      "Be clear and concise.",
      "Be specific and provide as much detail as possible.",
      "Be objective and avoid emotional language.",
      "Be respectful and avoid personal attacks.",
      "Proofread your complaint before submitting it."
    ]
  },
  hindi: {
    newComplaint: "नई शिकायत",
    complaintForm: "शिकायत प्रपत्र",
    success: "सफलता",
    complaintSubmitted: "शिकायत सफलतापूर्वक जमा की गई!",
    error: "त्रुटि",
    complaintFailed: "शिकायत जमा करने में विफल",
    titleLabel: "शीर्षक",
    descriptionLabel: "विवरण",
    sectorLabel: "सेक्टर",
    submitButton: "जमा करें",
    uploadFiles: "फ़ाइलें अपलोड करें",
    dropFilesHere: "फ़ाइलें यहां छोड़ें, या फ़ाइलें चुनने के लिए क्लिक करें",
    audioRecording: "ऑडियो रिकॉर्डिंग",
    startRecording: "रिकॉर्डिंग शुरू करें",
    stopRecording: "रिकॉर्डिंग बंद करें",
    recordComplaint: "अपनी शिकायत रिकॉर्ड करें",
    platformExperience: "प्लेटफ़ॉर्म अनुभव",
    responseTime: "प्रतिक्रिया समय",
    accessibility: "अभिगम्यता",
    other: "अन्य",
    feedbackCategory: "प्रतिक्रिया श्रेणी",
    name: "नाम",
    email: "ईमेल",
    optional: "वैकल्पिक",
    required: "आवश्यक",
    selectState: "राज्य चुनें",
    selectDistrict: "जिला चुनें",
    dateOfIncident: "घटना की तिथि",
    languageSelect: "हिंदी",
    successStories: "सफलता की कहानियाँ",
    resources: "संसाधन",
    peerSupport: "पीयर सपोर्ट",
    liveQA: "लाइव प्रश्नोत्तर",
    aiHelp: "एआई हेल्प",
    changeLanguage: "भाषा बदलें",
    viewDashboard: "डैशबोर्ड देखें",
    loading: "लोड हो रहा है...",
    complaintNotFound: "शिकायत नहीं मिली",
    backToComplaints: "शिकायतों पर वापस जाएं",
    by: "द्वारा",
    anonymous: "अनाम",
    submittedOn: "जमा करने की तिथि",
    updateStatus: "स्थिति अपडेट करें",
    updates: "अपडेट्स",
    addUpdate: "अपडेट जोड़ें...",
    adding: "जोड़ा जा रहा है...",
    status: {
      pending: "लंबित",
      in_progress: "प्रगति में",
      resolved: "हल किया गया",
      rejected: "अस्वीकृत"
    },
    helpTitle: "हम आपकी मदद कैसे कर सकते हैं?",
    helpStep1Title: "चरण 1: अपनी समस्या का वर्णन करें",
    helpStep1Content: "जिस समस्या का आप सामना कर रहे हैं, उसका स्पष्ट और संक्षिप्त वर्णन करें। तिथियों, समयों, स्थानों और शामिल लोगों सहित जितना संभव हो उतना विवरण प्रदान करें।",
    helpStep2Title: "चरण 2: सहायक साक्ष्य एकत्र करें",
    helpStep2Items: [
      "कोई भी दस्तावेज़, फ़ोटो, वीडियो या अन्य साक्ष्य एकत्र करें जो आपके दावे का समर्थन करते हैं।",
      "सुनिश्चित करें कि आपका साक्ष्य प्रासंगिक है और स्पष्ट रूप से लेबल किया गया है।",
      "यदि आपके पास गवाह हैं, तो उनसे लिखित बयान देने के लिए कहें।"
    ],
    helpStep3Title: "चरण 3: अपनी शिकायत जमा करें",
    helpStep3Content: "एक बार जब आप सभी आवश्यक जानकारी एकत्र कर लेते हैं, तो हमारे ऑनलाइन फॉर्म के माध्यम से अपनी शिकायत जमा करें। सभी आवश्यक फ़ील्ड भरना और कोई भी सहायक साक्ष्य संलग्न करना सुनिश्चित करें।",
    helpTipsTitle: "एक प्रभावी शिकायत लिखने के लिए युक्तियाँ",
    helpTipsItems: [
      "स्पष्ट और संक्षिप्त रहें।",
      "विशिष्ट रहें और जितना संभव हो उतना विवरण प्रदान करें।",
      "वस्तुनिष्ठ रहें और भावनात्मक भाषा से बचें।",
      "सम्मानजनक रहें और व्यक्तिगत हमलों से बचें।",
      "जमा करने से पहले अपनी शिकायत को प्रूफरीड करें।"
    ]
  },
  bengali: {
    newComplaint: "নতুন অভিযোগ",
    complaintForm: "অভিযোগ ফর্ম",
    success: "সাফল্য",
    complaintSubmitted: "অভিযোগ সফলভাবে জমা দেওয়া হয়েছে!",
    error: "ত্রুটি",
    complaintFailed: "অভিযোগ জমা দিতে ব্যর্থ",
    titleLabel: "শিরোনাম",
    descriptionLabel: "বর্ণনা",
    sectorLabel: "খাত",
    submitButton: "জমা দিন",
    uploadFiles: "ফাইল আপলোড করুন",
    dropFilesHere: "এখানে ফাইল ড্রপ করুন, অথবা ফাইল নির্বাচন করতে ক্লিক করুন",
    audioRecording: "অডিও রেকর্ডিং",
    startRecording: "রেকর্ডিং শুরু করুন",
    stopRecording: "রেকর্ডিং বন্ধ করুন",
    recordComplaint: "আপনার অভিযোগ রেকর্ড করুন",
    platformExperience: "প্ল্যাটফর্ম অভিজ্ঞতা",
    responseTime: "প্রতিক্রিয়া সময়",
    accessibility: "অ্যাক্সেসযোগ্যতা",
    other: "অন্যান্য",
    feedbackCategory: "ফিডব্যাক বিভাগ",
    name: "নাম",
    email: "ইমেইল",
    optional: "ঐচ্ছিক",
    required: "আবশ্যক",
    selectState: "রাজ্য নির্বাচন করুন",
    selectDistrict: "জেলা নির্বাচন করুন",
    dateOfIncident: "ঘটনার তারিখ",
    languageSelect: "বাংলা",
    successStories: "সাফল্যের গল্প",
    resources: "সম্পদ",
    peerSupport: "পিয়ার সাপোর্ট",
    liveQA: "লাইভ প্রশ্নোত্তর",
    aiHelp: "এআই সাহায্য",
    changeLanguage: "ভাষা পরিবর্তন করুন",
    viewDashboard: "ড্যাশবোর্ড দেখুন",
    loading: "লোড হচ্ছে...",
    complaintNotFound: "অভিযোগ পাওয়া যায়নি",
    backToComplaints: "অভিযোগে ফিরে যান",
    by: "দ্বারা",
    anonymous: "বেনামী",
    submittedOn: "জমা দেওয়ার তারিখ",
    updateStatus: "স্থিতি আপডেট করুন",
    updates: "আপডেট",
    addUpdate: "আপডেট যোগ করুন...",
    adding: "যোগ করা হচ্ছে...",
    status: {
      pending: "বিচারাধীন",
      in_progress: "প্রক্রিয়াধীন",
      resolved: "সমাধান করা হয়েছে",
      rejected: "প্রত্যাখ্যান করা হয়েছে"
    },
    helpTitle: "আমরা কিভাবে আপনাকে সাহায্য করতে পারি?",
    helpStep1Title: "ধাপ 1: আপনার সমস্যা বর্ণনা করুন",
    helpStep1Content: "আপনি যে সমস্যার সম্মুখীন হচ্ছেন তার একটি স্পষ্ট এবং সংক্ষিপ্ত বিবরণ দিন। তারিখ, সময়, স্থান এবং জড়িত ব্যক্তি সহ যতটা সম্ভব বিস্তারিত তথ্য প্রদান করুন।",
    helpStep2Title: "ধাপ 2: সহায়ক প্রমাণ সংগ্রহ করুন",
    helpStep2Items: [
      "যেকোনো নথি, ছবি, ভিডিও বা অন্যান্য প্রমাণ সংগ্রহ করুন যা আপনার দাবি সমর্থন করে।",
      "নিশ্চিত করুন যে আপনার প্রমাণ প্রাসঙ্গিক এবং স্পষ্টভাবে লেবেল করা হয়েছে।",
      "যদি আপনার সাক্ষী থাকে, তাহলে তাদের একটি লিখিত বিবৃতি প্রদান করতে বলুন।"
    ],
    helpStep3Title: "ধাপ 3: আপনার অভিযোগ জমা দিন",
    helpStep3Content: "একবার আপনি সমস্ত প্রয়োজনীয় তথ্য সংগ্রহ করার পরে, আমাদের অনলাইন ফর্মের মাধ্যমে আপনার অভিযোগ জমা দিন। সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করতে এবং কোনো সহায়ক প্রমাণ সংযুক্ত করতে ভুলবেন না।",
    helpTipsTitle: "একটি কার্যকর অভিযোগ লেখার জন্য টিপস",
    helpTipsItems: [
      "স্পষ্ট এবং সংক্ষিপ্ত হন।",
      "নির্দিষ্ট হন এবং যতটা সম্ভব বিস্তারিত তথ্য প্রদান করুন।",
      "বস্তুনিষ্ঠ হন এবং আবেগপূর্ণ ভাষা এড়িয়ে চলুন।",
      "সম্মানজনক হন এবং ব্যক্তিগত আক্রমণ এড়িয়ে চলুন।",
      "জমা দেওয়ার আগে আপনার অভিযোগটি প্রুফরিড করুন।"
    ]
  },
  telugu: {
    newComplaint: "కొత్త ఫిర్యాదు",
    complaintForm: "ఫిర్యాదు ఫారం",
    success: "విజయం",
    complaintSubmitted: "ఫిర్యాదు విజయవంతంగా సమర్పించబడింది!",
    error: "లోపం",
    complaintFailed: "ఫిర్యాదును సమర్పించడంలో విఫలం",
    titleLabel: "శీర్షిక",
    descriptionLabel: "వివరణ",
    sectorLabel: "రంగం",
    submitButton: "సమర్పించు",
    uploadFiles: "ఫైళ్ళను అప్లోడ్ చేయండి",
    dropFilesHere: "ఇక్కడ ఫైళ్ళను డ్రాప్ చేయండి లేదా ఫైళ్ళను ఎంచుకోవడానికి క్లిక్ చేయండి",
    audioRecording: "ఆడియో రికార్డింగ్",
    startRecording: "రికార్డింగ్ ప్రారంభించండి",
    stopRecording: "రికార్డింగ్ ఆపండి",
    recordComplaint: "మీ ఫిర్యాదును రికార్డ్ చేయండి",
    platformExperience: "ప్లాట్‌ఫాం అనుభవం",
    responseTime: "స్పందన సమయం",
    accessibility: "ప్రాప్యత",
    other: "ఇతర",
    feedbackCategory: "అభిప్రాయ వర్గం",
    name: "పేరు",
    email: "ఇమెయిల్",
    optional: "ఐచ్ఛికం",
    required: "అవసరం",
    selectState: "రాష్ట్రాన్ని ఎంచుకోండి",
    selectDistrict: "జిల్లాను ఎంచుకోండి",
    dateOfIncident: "సంఘటన జరిగిన తేదీ",
    languageSelect: "తెలుగు",
    successStories: "విజయ గాథలు",
    resources: "వనరులు",
    peerSupport: "సహాయ సహకారాలు",
    liveQA: "లైవ్ ప్రశ్నలు & సమాధానాలు",
    aiHelp: "AI సహాయం",
    changeLanguage: "భాష మార్చండి",
    viewDashboard: "డాష్‌బోర్డ్‌ను చూడండి",
    loading: "లోడ్ అవుతోంది...",
    complaintNotFound: "ఫిర్యాదు కనుగొనబడలేదు",
    backToComplaints: "ఫిర్యాదులకు తిరిగి వెళ్ళండి",
    by: "ద్వారా",
    anonymous: "అజ్ఞాత",
    submittedOn: "సమర్పించిన తేదీ",
    updateStatus: "స్థితిని నవీకరించండి",
    updates: "నవీకరణలు",
    addUpdate: "నవీకరణను జోడించండి...",
    adding: "జోడిస్తోంది...",
    status: {
      pending: "పెండింగ్",
      in_progress: "ప్రగతిలో ఉంది",
      resolved: "పరిష్కరించబడింది",
      rejected: "తిరస్కరించబడింది"
    },
    helpTitle: "మేము మీకు ఎలా సహాయం చేయగలము?",
    helpStep1Title: "దశ 1: మీ సమస్యను వివరించండి",
    helpStep1Content: "మీరు ఎదుర్కొంటున్న సమస్యను స్పష్టంగా మరియు సంక్షిప్తంగా వివరించండి. తేదీలు, సమయాలు, స్థానాలు మరియు పాల్గొన్న వ్యక్తులతో సహా వీలైనంత ఎక్కువ వివరాలను అందించండి.",
    helpStep2Title: "దశ 2: సహాయక సాక్ష్యాలను సేకరించండి",
    helpStep2Items: [
      "మీ దావాకు మద్దతు ఇచ్చే ఏదైనా పత్రాలు, ఫోటోలు, వీడియోలు లేదా ఇతర సాక్ష్యాలను సేకరించండి.",
      "మీ సాక్ష్యం సంబంధితంగా ఉందని మరియు స్పష్టంగా లేబుల్ చేయబడిందని నిర్ధారించుకోండి.",
      "మీకు సాక్షులు ఉంటే, వారిని వ్రాతపూర్వక ప్రకటనను అందించమని అడగండి."
    ],
    helpStep3Title: "దశ 3: మీ ఫిర్యాదును సమర్పించండి",
    helpStep3Content: "మీరు అవసరమైన మొత్తం సమాచారాన్ని సేకరించిన తర్వాత, మా ఆన్‌లైన్ ఫారమ్ ద్వారా మీ ఫిర్యాదును సమర్పించండి. అవసరమైన అన్ని ఫీల్డ్‌లను పూరించండి మరియు ఏదైనా సహాయక సాక్ష్యాలను జతచేయండి.",
    helpTipsTitle: "సమర్థవంతమైన ఫిర్యాదును వ్రాయడానికి చిట్కాలు",
    helpTipsItems: [
      "స్పష్టంగా మరియు సంక్షిప్తంగా ఉండండి.",
      "నిర్దిష్టంగా ఉండండి మరియు వీలైనంత ఎక్కువ వివరాలను అందించండి.",
      "నిష్పాక్షికంగా ఉండండి మరియు భావోద్వేగ భాషను నివారించండి.",
      "గౌరవంగా ఉండండి మరియు వ్యక్తిగత దాడులను నివారించండి.",
      "సమర్పించే ముందు మీ ఫిర్యాదును ప్రూఫ్‌రీడ్ చేయండి."
    ]
  },
  marathi: {
    newComplaint: "नवीन तक्रार",
    complaintForm: "तक्रार अर्ज",
    success: "यश",
    complaintSubmitted: "तक्रार यशस्वीरित्या सबमिट केली!",
    error: "त्रुटी",
    complaintFailed: "तक्रार सबमिट करण्यात अयशस्वी",
    titleLabel: "शीर्षक",
    descriptionLabel: "वर्णन",
    sectorLabel: "क्षेत्र",
    submitButton: "सबमिट करा",
    uploadFiles: "फाइल अपलोड करा",
    dropFilesHere: "फाइल येथे ड्रॉप करा, किंवा फाइल निवडण्यासाठी क्लिक करा",
    audioRecording: "ऑडिओ रेकॉर्डिंग",
    startRecording: "रेकॉर्डिंग सुरू करा",
    stopRecording: "रेकॉर्डिंग थांबवा",
    recordComplaint: "तुमची तक्रार रेकॉर्ड करा",
    platformExperience: "प्लॅटफॉर्म अनुभव",
    responseTime: "प्रतिक्रिया वेळ",
    accessibility: "प्रवेशयोग्यता",
    other: "इतर",
    feedbackCategory: "अभिप्राय श्रेणी",
    name: "नाव",
    email: "ईमेल",
    optional: "वैकल्पिक",
    required: "आवश्यक",
    selectState: "राज्य निवडा",
    selectDistrict: "जिल्हा निवडा",
    dateOfIncident: "घटनेची तारीख",
    languageSelect: "मराठी",
    successStories: "यशस्वी कथा",
    resources: "संसाधने",
    peerSupport: "समवयस्क समर्थन",
    liveQA: "लाइव्ह प्रश्नोत्तर",
    aiHelp: "एआय मदत",
    changeLanguage: "भाषा बदला",
    viewDashboard: "डॅशबोर्ड पहा",
    loading: "लोड होत आहे...",
    complaintNotFound: "तक्रार आढळली नाही",
    backToComplaints: "तक्रारींवर परत जा",
    by: "द्वारे",
    anonymous: "अनामित",
    submittedOn: "सादर करण्याची तारीख",
    updateStatus: "स्थिती अद्यतनित करा",
    updates: "अद्यतने",
    addUpdate: "अद्यतन जोडा...",
    adding: "जोडत आहे...",
    status: {
      pending: "प्रलंबित",
      in_progress: "प्रगतीपथावर",
      resolved: "निराकरण झाले",
      rejected: "नाकारले"
    },
    helpTitle: "आम्ही तुम्हाला कशी मदत करू शकतो?",
    helpStep1Title: "चरण 1: तुमची समस्या सांगा",
    helpStep1Content: "तुम्ही ज्या समस्येचा सामना करत आहात त्याचे स्पष्ट आणि संक्षिप्त वर्णन करा. तारखा, वेळा, स्थाने आणि सहभागी लोकांसह शक्य तितकी माहिती द्या.",
    helpStep2Title: "चरण 2: सहाय्यक पुरावे गोळा करा",
    helpStep2Items: [
      "तुमच्या दाव्याला समर्थन देणारी कोणतीही कागदपत्रे, फोटो, व्हिडिओ किंवा इतर पुरावे गोळा करा.",
      "खात्री करा की तुमचा पुरावा संबंधित आहे आणि स्पष्टपणे लेबल केलेला आहे.",
      "जर तुमच्याकडे साक्षीदार असतील, तर त्यांना लेखी निवेदन देण्यास सांगा."
    ],
    helpStep3Title: "चरण 3: तुमची तक्रार सबमिट करा",
    helpStep3Content: "एकदा तुम्ही सर्व आवश्यक माहिती गोळा केल्यानंतर, आमच्‍या ऑनलाइन फॉर्मद्वारे तुमची तक्रार सबमिट करा. सर्व आवश्यक फील्ड भरणे आणि कोणताही सहाय्यक पुरावा जोडणे सुनिश्चित करा.",
    helpTipsTitle: "एक प्रभावी तक्रार लिहिण्‍यासाठी टिप्‍स",
    helpTipsItems: [
      "स्पष्ट आणि संक्षिप्त रहा.",
      "विशिष्ट रहा आणि शक्य तितकी माहिती द्या.",
      "वस्तुनिष्ठ रहा आणि भावनिक भाषा टाळा.",
      "आदरणीय रहा आणि वैयक्तिक हल्ले टाळा.",
      "सबमिट करण्यापूर्वी तुमच्या तक्रारीची प्रूफरीड करा."
    ]
  },
  tamil: {
    newComplaint: "புதிய புகார்",
    complaintForm: "புகார் படிவம்",
    success: "வெற்றி",
    complaintSubmitted: "புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!",
    error: "பிழை",
    complaintFailed: "புகாரை சமர்ப்பிக்க முடியவில்லை",
    titleLabel: "தலைப்பு",
    descriptionLabel: "விளக்கம்",
    sectorLabel: "துறை",
    submitButton: "சமர்ப்பிக்கவும்",
    uploadFiles: "கோப்புகளை பதிவேற்றுக",
    dropFilesHere: "கோப்புகளை இங்கே விடுங்கள், அல்லது கோப்புகளைத் தேர்ந்தெடுக்க கிளிக் செய்க",
    audioRecording: "ஆடியோ பதிவு",
    startRecording: "பதிவை தொடங்குக",
    stopRecording: "பதிவை நிறுத்து",
    recordComplaint: "உங்கள் புகாரை பதிவு செய்க",
    platformExperience: "தளம் அனுபவம்",
    responseTime: "பதில் நேரம்",
    accessibility: "அணுகல்தன்மை",
    other: "மற்றவை",
    feedbackCategory: "கருத்து வகை",
    name: "பெயர்",
    email: "மின்னஞ்சல்",
    optional: "விருப்பம்",
    required: "தேவை",
    selectState: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
    selectDistrict: "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
    dateOfIncident: "சம்பவத்தின் தேதி",
    languageSelect: "தமிழ்",
    successStories: "வெற்றிக் கதைகள்",
    resources: "ஆதாரங்கள்",
    peerSupport: "சக ஆதரவு",
    liveQA: "நேரடி கேள்வி பதில்",
    aiHelp: "AI உதவி",
    changeLanguage: "மொழியை மாற்றுக",
    viewDashboard: "டாஷ்போர்டைக் காண்க",
    loading: "ஏற்றுகிறது...",
    complaintNotFound: "புகார் காணப்படவில்லை",
    backToComplaints: "புகார்களுக்குத் திரும்பு",
    by: "மூலம்",
    anonymous: "அநாமதேய",
    submittedOn: "சமர்ப்பித்த தேதி",
    updateStatus: "நிலையை புதுப்பிக்கவும்",
    updates: "புதுப்பிப்புகள்",
    addUpdate: "புதுப்பிப்பைச் சேர்க்கவும்...",
    adding: "சேர்க்கிறது...",
    status: {
      pending: "நிலுவையில் உள்ளது",
      in_progress: "நடந்து கொண்டிருக்கிறது",
      resolved: "தீர்க்கப்பட்டது",
      rejected: "நிராகரிக்கப்பட்டது"
    },
    helpTitle: "நாங்கள் உங்களுக்கு எப்படி உதவ முடியும்?",
    helpStep1Title: "படி 1: உங்கள் சிக்கலை விவரிக்கவும்",
    helpStep1Content: "நீங்கள் எதிர்கொள்ளும் சிக்கலை தெளிவாகவும் சுருக்கமாகவும் விவரிக்கவும். தேதிகள், நேரங்கள், இடங்கள் மற்றும் சம்பந்தப்பட்ட நபர்கள் உட்பட முடிந்தவரை விவரங்களை வழங்கவும்.",
    helpStep2Title: "படி 2: துணை ஆதாரங்களை சேகரிக்கவும்",
    helpStep2Items: [
      "உங்கள் கூற்றை ஆதரிக்கும் எந்த ஆவணங்கள், புகைப்படங்கள், வீடியோக்கள் அல்லது பிற ஆதாரங்களை சேகரிக்கவும்.",
      "உங்கள் ஆதாரம் பொருத்தமானதாகவும் தெளிவாக லேபிளிடப்பட்டதாகவும் இருப்பதை உறுதிப்படுத்திக் கொள்ளுங்கள்.",
      "உங்களிடம் சாட்சிகள் இருந்தால், அவர்களிடம் எழுத்துப்பூர்வ அறிக்கையை வழங்கும்படி கேளுங்கள்."
    ],
    helpStep3Title: "படி 3: உங்கள் புகாரை சமர்ப்பிக்கவும்",
    helpStep3Content: "தேவையான அனைத்து தகவல்களையும் நீங்கள் சேகரித்தவுடன், எங்கள் ஆன்லைன் படிவம் மூலம் உங்கள் புகாரை சமர்ப்பிக்கவும். தேவையான அனைத்து புலங்களையும் பூர்த்தி செய்து, ஏதேனும் துணை ஆதாரங்களை இணைக்க மறக்காதீர்கள்.",
    helpTipsTitle: "ஒரு பயனுள்ள புகாரை எழுதுவதற்கான உதவிக்குறிப்புகள்",
    helpTipsItems: [
      "தெளிவாகவும் சுருக்கமாகவும் இருங்கள்.",
      "குறிப்பாக இருங்கள் மற்றும் முடிந்தவரை விவரங்களை வழங்கவும்.",
      "புறநிலையாக இருங்கள் மற்றும் உணர்ச்சிவசப்பட்ட மொழியைத் தவிர்க்கவும்.",
      "மரியாதையாக இருங்கள் மற்றும் தனிப்பட்ட தாக்குதல்களைத் தவிர்க்கவும்.",
      "சமர்ப்பிக்கும் முன் உங்கள் புகாரை சரிபார்க்கவும்."
    ]
  },
  gujarati: {
    newComplaint: "નવી ફરિયાદ",
    complaintForm: "ફરિયાદ ફોર્મ",
    success: "સફળતા",
    complaintSubmitted: "ફરિયાદ સફળતાપૂર્વક સબમિટ થઈ!",
    error: "ભૂલ",
    complaintFailed: "ફરિયાદ સબમિટ કરવામાં નિષ્ફળ",
    titleLabel: "શીર્ષક",
    descriptionLabel: "વર્ણન",
    sectorLabel: "ક્ષેત્ર",
    submitButton: "સબમિટ કરો",
    uploadFiles: "ફાઇલો અપલોડ કરો",
    dropFilesHere: "ફાઇલો અહીં મૂકો, અથવા ફાઇલો પસંદ કરવા માટે ક્લિક કરો",
    audioRecording: "ઓડિયો રેકોર્ડિંગ",
    startRecording: "રેકોર્ડિંગ શરૂ કરો",
    stopRecording: "રેકોર્ડિંગ બંધ કરો",
    recordComplaint: "તમારી ફરિયાદ રેકોર્ડ કરો",
    platformExperience: "પ્લેટફોર્મ અનુભવ",
    responseTime: "પ્રતિભાવ સમય",
    accessibility: "સુલભતા",
    other: "અન્ય",
    feedbackCategory: "પ્રતિસાદ શ્રેણી",
    name: "નામ",
    email: "ઇમેઇલ",
    optional: "વૈકલ્પિક",
    required: "જરૂરી",
    selectState: "રાજ્ય પસંદ કરો",
    selectDistrict: "જિલ્લો પસંદ કરો",
    dateOfIncident: "ઘટનાની તારીખ",
    languageSelect: "ગુજરાતી",
    successStories: "સફળતાની વાર્તાઓ",
    resources: "સંસાધનો",
    peerSupport: "પીઅર સપોર્ટ",
    liveQA: "લાઇવ પ્રશ્નો અને જવાબો",
    aiHelp: "એઆઇ મદદ",
    changeLanguage: "ભાષા બદલો",
    viewDashboard: "ડેશબોર્ડ જુઓ",
    loading: "લોડ થઈ રહ્યું છે...",
    complaintNotFound: "ફરિયાદ મળી નથી",
    backToComplaints: "ફરિયાદો પર પાછા જાઓ",
    by: "દ્વારા",
    anonymous: "અનામી",
    submittedOn: "સબમિટ કરવાની તારીખ",
    updateStatus: "સ્થિતિ અપડેટ કરો",
    updates: "અપડેટ્સ",
    addUpdate: "અપડેટ ઉમેરો...",
    adding: "ઉમેરી રહ્યા છે...",
    status: {
      pending: "બાકી",
      in_progress: "ચાલુ છે",
      resolved: "ઉકેલાઈ ગયું",
      rejected: "નકારવામાં આવ્યું"
    },
    helpTitle: "અમે તમને કેવી રીતે મદદ કરી શકીએ?",
    helpStep1Title: "પગલું 1: તમારી સમસ્યાનું વર્ણન કરો",
    helpStep1Content: "તમે જે સમસ્યાનો સામનો કરી રહ્યા છો તેનું સ્પષ્ટ અને સંક્ષિપ્ત વર્ણન કરો. તારીખો, સમય, સ્થાનો અને સંડોવાયેલા લોકો સહિત શક્ય તેટલી વધુ વિગતો પ્રદાન કરો.",
    helpStep2Title: "પગલું 2: સહાયક પુરાવા એકત્રિત કરો",
    helpStep2Items: [
      "કોઈપણ દસ્તાવેજો, ફોટા, વિડિયો અથવા અન્ય પુરાવા એકત્રિત કરો જે તમારા દાવાને સમર્થન આપે છે.",
      "ખાતરી કરો કે તમારો પુરાવો સુસંગત છે અને સ્પષ્ટ રીતે લેબલ થયેલ છે.",
      "જો તમારી પાસે સાક્ષીઓ હોય, તો તેમને લેખિત નિવેદન આપવા માટે કહો."
    ],
    helpStep3Title: "પગલું 3: તમારી ફરિયાદ સબમિટ કરો",
    helpStep3Content: "એકવાર તમે બધી જરૂરી માહિતી એકત્રિત કરી લો, પછી અમારા ઓનલાઈન ફોર્મ દ્વારા તમારી ફરિયાદ સબમિટ કરો. બધા જરૂરી ફીલ્ડ્સ ભરવા અને કોઈપણ સહાયક પુરાવા જોડવાનું સુનિશ્ચિત કરો.",
    helpTipsTitle: "એક અસરકારક ફરિયાદ લખવા માટે ટિપ્સ",
    helpTipsItems: [
      "સ્પષ્ટ અને સંક્ષિપ્ત રહો.",
      "ચોક્કસ રહો અને શક્ય તેટલી વધુ વિગતો પ્રદાન કરો.",
      "નિષ્પક્ષ બનો અને ભાવનાત્મક ભાષા ટાળો.",
      "આદરણીય બનો અને વ્યક્તિગત હુમલા ટાળો.",
      "સબમિટ કરતા પહેલા તમારી ફરિયાદને પ્રૂફરીડ કરો."
    ]
  },
  kannada: {
    newComplaint: "ಹೊಸ ದೂರು",
    complaintForm: "ದೂರು ನಮೂನೆ",
    success: "ಯಶಸ್ಸು",
    complaintSubmitted: "ದೂರನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!",
    error: "ದೋಷ",
    complaintFailed: "ದೂರು ಸಲ್ಲಿಸಲು ವಿಫಲವಾಗಿದೆ",
    titleLabel: "ಶೀರ್ಷಿಕೆ",
    descriptionLabel: "ವಿವರಣೆ",
    sectorLabel: "ಕ್ಷೇತ್ರ",
    submitButton: "ಸಲ್ಲಿಸು",
    uploadFiles: "ಫೈಲ್‌ಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    dropFilesHere: "ಫೈಲ್‌ಗಳನ್ನು ಇಲ್ಲಿ ಬಿಡಿ, ಅಥವಾ ಫೈಲ್‌ಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
    audioRecording: "ಆಡಿಯೋ ರೆಕಾರ್ಡಿಂಗ್",
    startRecording: "ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
    stopRecording: "ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ",
    recordComplaint: "ನಿಮ್ಮ ದೂರನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ",
    platformExperience: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅನುಭವ",
    responseTime: "ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯ",
    accessibility: "ಪ್ರವೇಶಿಸುವಿಕೆ",
    other: "ಇತರೆ",
    feedbackCategory: "ಪ್ರತಿಕ್ರಿಯೆ ವರ್ಗ",
    name: "ಹೆಸರು",
    email: "ಇಮೇಲ್",
    optional: "ಐಚ್ಛಿಕ",
    required: "ಅಗತ್ಯವಿದೆ",
    selectState: "ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    selectDistrict: "ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    dateOfIncident: "ಘಟನೆಯ ದಿನಾಂಕ",
    languageSelect: "ಕನ್ನಡ",
    successStories: "ಯಶಸ್ಸಿನ ಕಥೆಗಳು",
    resources: "ಸಂಪನ್ಮೂಲಗಳು",
    peerSupport: "ಪೀರ್ ಬೆಂಬಲ",
    liveQA: "ಲೈವ್ ಪ್ರಶ್ನೋತ್ತರ",
    aiHelp: "AI ಸಹಾಯ",
    changeLanguage: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
    viewDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ವೀಕ್ಷಿಸಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    complaintNotFound: "ದೂರು ಕಂಡುಬಂದಿಲ್ಲ",
    backToComplaints: "ದೂರುಗಳಿಗೆ ಹಿಂತಿರುಗಿ",
    by: "ಮೂಲಕ",
    anonymous: "ಅನಾಮಧೇಯ",
    submittedOn: "ಸಲ್ಲಿಸಿದ ದಿನಾಂಕ",
    updateStatus: "ಸ್ಥಿತಿಯನ್ನು ನವೀಕರಿಸಿ",
    updates: "ನವೀಕರಣಗಳು",
    addUpdate: "ನವೀಕರಣವನ್ನು ಸೇರಿಸಿ...",
    adding: "ಸೇರಿಸಲಾಗುತ್ತಿದೆ...",
    status: {
      pending: " ಬಾಕಿ ಉಳಿದಿದೆ",
      in_progress: "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
      resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
      rejected: "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ"
    },
    helpTitle: "ನಾವು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
    helpStep1Title: "ಹಂತ 1: ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ",
    helpStep1Content: "ನೀವು ಎದುರಿಸುತ್ತಿರುವ ಸಮಸ್ಯೆಯನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ಮತ್ತು ಸಂಕ್ಷಿಪ್ತವಾಗಿ ವಿವರಿಸಿ. ದಿನಾಂಕಗಳು, ಸಮಯಗಳು, ಸ್ಥಳಗಳು ಮತ್ತು ಒಳಗೊಂಡಿರುವ ಜನರು ಸೇರಿದಂತೆ ಸಾಧ್ಯವಾದಷ್ಟು ವಿವರಗಳನ್ನು ಒದಗಿಸಿ.",
    helpStep2Title: "ಹಂತ 2: ಬೆಂಬಲ ಪುರಾವೆಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ",
    helpStep2Items: [
      "ನಿಮ್ಮ ಹಕ್ಕನ್ನು ಬೆಂಬಲಿಸುವ ಯಾವುದೇ ದಾಖಲೆಗಳು, ಫೋಟೋಗಳು, ವೀಡಿಯೊಗಳು ಅಥವಾ ಇತರ ಪುರಾವೆಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ.",
      "ನಿಮ್ಮ ಪುರಾವೆ ಪ್ರಸ್ತುತವಾಗಿದೆ ಮತ್ತು ಸ್ಪಷ್ಟವಾಗಿ ಲೇಬಲ್ ಮಾಡಲ್ಪಟ್ಟಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.",
      "ನೀವು ಸಾಕ್ಷಿಗಳನ್ನು ಹೊಂದಿದ್ದರೆ, ಲಿಖಿತ ಹೇಳಿಕೆಯನ್ನು ನೀಡಲು ಅವರನ್ನು ಕೇಳಿ."
    ],
    helpStep3Title: "ಹಂತ 3: ನಿಮ್ಮ ದೂರನ್ನು ಸಲ್ಲಿಸಿ",
    helpStep3Content: "ನೀವು ಅಗತ್ಯವಿರುವ ಎಲ್ಲಾ ಮಾಹಿತಿಯನ್ನು ಸಂಗ್ರಹಿಸಿದ ನಂತರ, ನಮ್ಮ ಆನ್‌ಲೈನ್ ಫಾರ್ಮ್ ಮೂಲಕ ನಿಮ್ಮ ದೂರನ್ನು ಸಲ್ಲಿಸಿ. ಅಗತ್ಯವಿರುವ ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಲು ಮತ್ತು ಯಾವುದೇ ಬೆಂಬಲ ಪುರಾವೆಗಳನ್ನು ಲಗತ್ತಿಸಲು ಮರೆಯದಿರಿ.",
    helpTipsTitle: "ಪರಿಣಾಮಕಾರಿ ದೂರು ಬರೆಯಲು ಸಲಹೆಗಳು",
    helpTipsItems: [
      "ಸ್ಪಷ್ಟ ಮತ್ತು ಸಂಕ್ಷಿಪ್ತವಾಗಿರಿ.",
      "ನಿರ್ದಿಷ್ಟವಾಗಿರಿ ಮತ್ತು ಸಾಧ್ಯವಾದಷ್ಟು ವಿವರಗಳನ್ನು ಒದಗಿಸಿ.",
      "ವಸ್ತುನಿಷ್ಠವಾಗಿರಿ ಮತ್ತು ಭಾವನಾತ್ಮಕ ಭಾಷೆಯನ್ನು ತಪ್ಪಿಸಿ.",
      "ಗೌರವದಿಂದಿರಿ ಮತ್ತು ವೈಯಕ್ತಿಕ ದಾಳಿಗಳನ್ನು ತಪ್ಪಿಸಿ.",
      "ಸಲ್ಲಿಸುವ ಮೊದಲು ನಿಮ್ಮ ದೂರನ್ನು ಪ್ರೂಫ್‌ರೀಡ್ ಮಾಡಿ."
    ]
  }
} as const;

const NewComplaint = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const { language } = useLanguage();

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [sectorId, setSectorId] = useState("");
  const [sectors, setSectors] = useState<Sector[]>([]);
  const [loading, setLoading] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [submissionType, setSubmissionType] = useState<SubmissionType>("complaint");
  const [isLanguageDialogOpen, setIsLanguageDialogOpen] = useState(false);
  const [files, setFiles] = useState<File[]>([]);
  const [feedbackCategory, setFeedbackCategory] = useState("");
  const [userName, setUserName] = useState("");
  const [userEmail, setUserEmail] = useState("");
  const [complimentRecipient, setComplimentRecipient] = useState("");
  const [selectedState, setSelectedState] = useState("");
  const [selectedDistrict, setSelectedDistrict] = useState("");
  const [selectedDate, setSelectedDate] = useState<Date | undefined>(undefined);

  const onDrop = useCallback((acceptedFiles: File[]) => {
    setFiles((prevFiles) => [...prevFiles, ...acceptedFiles]);
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop });

  const { mutate: createComplaint } = useMutation({
    mutationFn: async (complaintData: {
      title: string;
      description: string;
      sector_id: string;
      user_id: string;
      submission_type: SubmissionType;
      feedback_category?: string;
      compliment_recipient?: string;
      state?: string;
      district?: string;
